#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
}" > /etc/nginx/sites-available/default

service nginx restart
