#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx
mkdir /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-available/default

service nginx restart
