#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

echo "
defaults
    timeout connect 30s
    timeout client 30s
    timeout server 30s
    log global
    mode http
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    option forwardfor
    server 1543-web-01 54.210.47.110:80 check
    server 1543-web-02 54.210.47.110:80 check
listen stats
    bind :32700
    stats enable
    stats uri /" >> /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
