#!/usr/bin/env bash
# configure firewall that deney all incomming except SSH, HTTPS and HTTp

sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
